<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="For Senior Professionals Who Refuse to Be Replaced by a Script and want to lead with AI">

<title>Build Your Personal AI Operating System – Jitin Kapila | The AI Architect</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./img/jk-logo.svg" rel="icon" type="image/svg+xml">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-626b0fff7b0ff2cc043be631a594889b.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-b06389d186abb95cf90c726c83558e4d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/accordion/accordion.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script defer="" src="https://cloud.umami.is/script.js" data-website-id="aeaaf854-d53a-45ab-83d5-1963c96af264"></script>
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Person",
      "@id": "https://jitinkapila.com/#person",
      "name": "Jitin Kapila",
      "alternateName": "The AI Architect",
      "description": "AI Strategy Consultant and Acting CTO with 14 years of enterprise AI implementation experience across Fortune 500 companies",
      "url": "https://jitinkapila.com",
      "image": "https://jitinkapila.com/display_image.jpg",
      "jobTitle": "AI Strategy Consultant & Acting CTO",
      "worksFor": {
        "@type": "Organization",
        "name": "Independent Consultant"
      },
      "knowsAbout": [
        "Artificial Intelligence Strategy",
        "Enterprise Architecture",
        "Predictive Analytics",
        "Machine Learning",
        "Digital Transformation",
        "Decision-Focused AI"
      ],
      "alumniOf": {
        "@type": "EducationalOrganization",
        "name": "Mechanical Engineering & Applied Mathematics"
      },
      "sameAs": [
        "https://linkedin.com/in/jitinkapila",
        "https://github.com/jkapila",
        "https://x.com/jitinkapila",
        "https://youtube.com/@jitinkapila",
        "https://aicrosscurrent.substack.com/",
        "https://instagram.com/jitinkapila"
      ]
    },
    {
      "@type": "ProfessionalService",
      "@id": "https://jitinkapila.com/#service",
      "name": "The AI Architect - AI Strategy Consulting",
      "description": "AI Strategy Consulting and Enterprise AI Transformation for Fortune 500 companies. Specializing in cross-industry pattern recognition and decision-first AI implementation.",
      "url": "https://jitinkapila.com",
      "logo": "https://jitinkapila.com/favicon-32x32.png",
      "image": "https://jitinkapila.com/display_image.jpg",
      "founder": {
        "@id": "https://jitinkapila.com/#person"
      },
      "provider": {
        "@id": "https://jitinkapila.com/#person"
      },
      "areaServed": {
        "@type": "Place",
        "name": "Worldwide"
      },
      "serviceType": [
        "AI Strategy Consulting",
        "Enterprise AI Architecture",
        "AI Transformation Roadmaps",
        "Acting CTO Services",
        "AI Training & Coaching"
      ],
      "priceRange": "$$$$"
    },
    {
      "@type": "Course",
      "@id": "https://jitinkapila.com/bootcamp.html#course",
      "name": "The AI Architect Protocol",
      "description": "A 3-day intensive bootcamp that transforms how enterprise leaders think about AI strategy. Master the OLCD Protocol, AI-ART Matrix, and Blueprint Methodology.",
      "provider": {
        "@id": "https://jitinkapila.com/#person"
      },
      "url": "https://jitinkapila.com/bootcamp.html",
      "courseMode": "Online",
      "educationalLevel": "Executive",
      "educationalCredentialAwarded": "Certificate of Completion",
      "numberOfCredits": "3 days",
      "timeRequired": "P3D",
      "inLanguage": "en",
      "coursePrerequisites": "Director or above at enterprise organization with AI strategy responsibility",
      "teaches": [
        "OLCD Protocol (Observe → Learn → Create → Deploy)",
        "AI-ART Matrix framework",
        "Blueprint Methodology for AI transformation",
        "Cross-industry pattern recognition",
        "Decision-first AI implementation"
      ],
      "hasCourseInstance": {
        "@type": "CourseInstance",
        "courseMode": "Online",
        "courseWorkload": "P3D",
        "instructor": {
          "@id": "https://jitinkapila.com/#person"
        }
      },
      "offers": {
        "@type": "Offer",
        "price": "7999",
        "priceCurrency": "INR",
        "availability": "https://schema.org/LimitedAvailability",
        "validFrom": "2025-01-01",
        "url": "https://jitinkapila.com/bootcamp.html",
        "seller": {
          "@id": "https://jitinkapila.com/#person"
        },
        "priceValidUntil": "2025-12-31",
        "description": "Limited to 20 seats per cohort. Includes live sessions, framework library, 90-day roadmap, and lifetime access."
      }
    },
    {
      "@type": "WebSite",
      "@id": "https://jitinkapila.com/#website",
      "url": "https://jitinkapila.com",
      "name": "Jitin Kapila | The AI Architect",
      "description": "AI Strategy & Enterprise Architecture for Fortune 500 Leaders",
      "publisher": {
        "@id": "https://jitinkapila.com/#person"
      },
      "inLanguage": "en"
    }
  ]
}
</script>


<link rel="stylesheet" href="includes/mainpage.css">
<meta property="og:title" content="Build Your Personal AI Operating System – Jitin Kapila | The AI Architect">
<meta property="og:description" content="For Senior Professionals Who Refuse to Be Replaced by a Script and want to lead with AI">
<meta property="og:image" content="https://jitinkapila.com/img/display_image.jpg">
<meta property="og:site_name" content="Jitin Kapila | The AI Architect">
<meta name="twitter:title" content="Build Your Personal AI Operating System – Jitin Kapila | The AI Architect">
<meta name="twitter:description" content="For Senior Professionals Who Refuse to Be Replaced by a Script and want to lead with AI">
<meta name="twitter:image" content="https://jitinkapila.com/img/display_image.jpg">
<meta name="twitter:creator" content="@jitinkapila">
<meta name="twitter:site" content="@jitinkapila">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./img/jk-logo.svg" alt="" class="navbar-logo light-content">
    <img src="./img/jk-logo.svg" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">JITIN KAPILA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./consulting.html"> 
<span class="menu-text">Consulting</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./bootcamp.html" aria-current="page"> 
<span class="menu-text">Courses</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./vault.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://aicrosscurrent.substack.com/" target="_blank"> 
<span class="menu-text">Newsletter!</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content column-page" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Build Your Personal AI Operating System</h1>
<p class="subtitle lead">AI Profit OS | A 3 Day Intensive Course</p>
</div>

<div>
  <div class="description">
    <strong>For Senior Professionals Who Refuse to Be Replaced by a Script and want to lead with AI</strong>
  </div>
</div>


<div class="quarto-title-meta column-page">

    
  
    
  </div>
  


</header>


<div class="grid justify-center">
<div class="g-col-6 g-row-md-auto">
<div class="card">
<p><span class="card-title"><strong>FOUNDING COHORT</strong></span><br>
<span class="card-description">December 19-21, 2025</span></p>
</div>
</div>
<div class="g-col-6 g-row-md-auto">
<div class="card">
<p><span class="card-title"><strong>FORMAT</strong></span><br>
<span class="card-description">3 Days - Live - 7 PM - 10 PM IST</span></p>
</div>
</div>
<div class="g-col-6 g-row-md-auto">
<div class="card">
<p><span class="card-title"><strong>DELIVERY</strong></span><br>
<span class="card-description">Virtual + Lifetime Recordings</span></p>
</div>
</div>
<div class="g-col-6 g-row-md-auto">
<div class="card">
<p><span class="card-title"><strong>CLASS SIZE</strong></span><br>
<span class="card-description">Maximum 20 Participants</span></p>
</div>
</div>
</div>
<p><br></p>
<div class="padded bg-warm justify-center text-center">
<p><a href="https://cal.com/jitink-kriyalytics/strategy-consulting" class="btn-primary btn-large">Secure Founding Cohort Pricing - ₹7,999</a><br>
<br> <span class="eyebrow">Regular Price: ₹15,999 | Only 20 Seats Available</span></p>
</div>
<section id="the-market-isnt-waiting-for-you-to-catch-up" class="level2">
<h2 class="anchored" data-anchor-id="the-market-isnt-waiting-for-you-to-catch-up">The Market Isn’t Waiting for You to Catch Up</h2>
<ul>
<li>You’re managing $80M portfolios.</li>
<li>You’re leading teams of 50+ people.</li>
<li>You’re making decisions that move markets.</li>
</ul>
<p><strong>But you’re still doing manual data entry.</strong></p>
<p>Meanwhile, a 22-year-old with ChatGPT is doing your job faster.</p>
<p><strong>The gap is widening.</strong></p>
<p>Senior professionals are being replaced by efficient systems. Not because they lack expertise. Because they lack <strong>operational leverage</strong>.</p>
<p><strong>Stop watching. Start building.</strong></p>
</section>
<section id="this-training-is-for-you-if" class="level2 bg-warm">
<h2 class="anchored" data-anchor-id="this-training-is-for-you-if">This Training Is For You If:</h2>
<div class="checklist-grid">
<ul>
<li><strong>You’re a senior professional</strong> (10+ years experience) managing significant portfolios or P&amp;L<br>
</li>
<li><strong>You’re drowning in repetitive work</strong> that AI could handle, but don’t know where to start<br>
</li>
<li><strong>You’re afraid of obsolescence</strong> as younger, AI-fluent professionals move faster<br>
</li>
<li><strong>You’ve tried ChatGPT</strong> but can’t scale it beyond simple tasks into real operational leverage<br>
</li>
<li><strong>You manage teams</strong> and need to 10x their output without 10x-ing headcount<br>
</li>
<li><strong>You’re willing to invest 3 days</strong> to build a system that saves 10+ hours every week</li>
</ul>
</div>
</section>
<section id="this-training-is-not-for-you-if" class="level2 padded">
<h2 class="anchored" data-anchor-id="this-training-is-not-for-you-if">This Training Is NOT For You If:</h2>
<div class="disqualify-grid">
<ul>
<li>You’re new to your field (less than 5 years experience)</li>
<li>You want to “learn AI” for your resume without implementing anything</li>
<li>You’re looking for passive income schemes or get-rich-quick tactics</li>
<li>You expect AI to do 100% of your job (it won’t)</li>
<li>You’re not willing to invest 2-3 hours per week maintaining your AI systems</li>
<li>You want theory and certifications, not practical operational systems</li>
</ul>
</div>
</section>
<section id="proof-of-concept-the-grocery-chain-story" class="level2 padded bg-warm">
<h2 class="anchored" data-anchor-id="proof-of-concept-the-grocery-chain-story">Proof of Concept: The Grocery Chain Story</h2>
<blockquote class="blockquote">
<p><strong>The Context:</strong> A regional grocery chain with ₹50Cr annual revenue, operating 15 stores across 3 cities.</p>
<p><strong>The “Before” (Ambiguity &amp; Pain):</strong> - Lost 15% of inventory to spoilage (₹7.5Cr annual loss) - Manual ordering took 20 hours per week across all stores - No predictive capability - constantly over-ordering perishables - Supply chain decisions based on “gut feel” from 30-year veterans <strong>The AI-ART Intervention:</strong> We installed a Predictive Ordering Agent using simple Excel + OpenAI API (no coding, no data scientists, no million-dollar platforms).</p>
<p>The system: - Analyzed 3 years of sales data (already sitting in Excel) - Factored in weather patterns, local events, seasonality - Generated daily ordering recommendations per store - Learned from feedback (what sold, what spoiled)</p>
<p><strong>The “After” (ROI):</strong> - Spoilage reduced by 92% (saving ₹6.9Cr annually) - Ordering time reduced from 20 hours/week to 2 hours/week - Profit margins increased by ₹8.2Cr in first year - <strong>Total investment: ₹45,000 (including our training)</strong> <strong>ROI: 182x in Year 1.</strong></p>
</blockquote>
<p>This isn’t a unicorn story. This is what happens when senior professionals apply operational AI thinking to their existing expertise.</p>
<p><strong>You don’t need a PhD. You need a system.</strong></p>
</section>
<section id="before-this-training-after-this-training" class="level2 padded bg-contrast">
<h2 class="anchored" data-anchor-id="before-this-training-after-this-training"><span style="text-align: right; justify-items: center; margin: 0.5rem 0em;">Before This Training → After This Training</span></h2>
<div class="quarto-listing-grid">
<div class="card-dark disqualify-grid">
<p><span class="card-title"><strong>Before</strong></span></p>
<ul>
<li>Spending 20+ hours/week on repetitive analysis</li>
<li>Drowning in emails, reports, data entry</li>
<li>Can’t scale yourself without hiring more people</li>
<li>Watching younger professionals move faster with AI</li>
<li>Scared of being replaced by automation</li>
<li>Using ChatGPT for one-off tasks with no system</li>
<li>No operational leverage beyond your own hours</li>
</ul>
</div>
<div class="card-dark checklist-grid">
<p><span class="card-title"><strong>After</strong></span></p>
<ul>
<li>AI Profit OS handles 40% of repetitive workflow</li>
<li>Email processing, report generation, data analysis automated</li>
<li>10x team output without 10x headcount</li>
<li>You’re the AI-fluent leader others come to</li>
<li>You’re building the systems, not being replaced by them</li>
<li>Deep-Research Prompt System producing insights in minutes</li>
<li>Operational leverage: Your decisions scale 24/7</li>
</ul>
</div>
</div>
</section>
<section id="what-youll-build-in-3-days-the-ai-profit-os" class="level2 padded">
<h2 class="anchored" data-anchor-id="what-youll-build-in-3-days-the-ai-profit-os">What You’ll Build in 3 Days: The AI Profit OS</h2>
<div class="timeline">
<section id="day-1-objective-your-90-day-ai-roadmap" class="level3 timeline-item">
<h3 class="anchored" data-anchor-id="day-1-objective-your-90-day-ai-roadmap">Day 1: OBJECTIVE — Your 90-Day AI Roadmap</h3>
<p><strong>Morning: The AI Maturity Assessment</strong> - Map your current workflow: Where are you spending 80% of your time? - Identify automation opportunities using the OLCD diagnostic framework - Calculate your “time ROI” - what’s actually worth automating first? - Build your personalized 90-day AI implementation roadmap</p>
<p><strong>Afternoon: Quick Wins Workshop</strong> - Install your first AI agent (email processing or report generation) - See immediate time savings (2-5 hours/week from Day 1) - Understand the “AI-ART Matrix” - why most AI projects fail to scale - Learn the “Grocery Store Framework” - how to think about AI operationally</p>
<p><strong>Deliverable:</strong> Your 90-Day AI Roadmap + First AI agent deployed</p>
</section>
<section id="day-2-learner-the-deep-research-prompt-system" class="level3 timeline-item">
<h3 class="anchored" data-anchor-id="day-2-learner-the-deep-research-prompt-system">Day 2: LEARNER — The Deep-Research Prompt System</h3>
<p><strong>Morning: The Research Multiplier</strong> - Build your Deep-Research Prompt System (the Excel-based framework) - How to extract insights from data you already have - Pattern recognition across your domain (using AI to spot trends you’d miss) - Case study: How I saved ₹6.9Cr for the grocery chain using this system</p>
<p><strong>Afternoon: The Data Asset Library</strong> - Create your personal “Data Asset Library” template - Learn to structure your knowledge for AI consumption - Build your “Second Brain” that actually works (not just another note-taking system) - How to train AI on your specific domain expertise</p>
<p><strong>Deliverable:</strong> Deep-Research Prompt System + Data Asset Library template</p>
</section>
<section id="day-3-controller-diagnostic-governance-roi-calculator" class="level3 timeline-item">
<h3 class="anchored" data-anchor-id="day-3-controller-diagnostic-governance-roi-calculator">Day 3: CONTROLLER &amp; DIAGNOSTIC — Governance + ROI Calculator</h3>
<p><strong>Morning: AI Governance Playbooks</strong><br>
- How to ensure AI output quality (avoid garbage-in-garbage-out) - Build review systems that catch AI mistakes before they matter - Team training: How to get your team using AI without breaking things - The “Human-in-the-Loop” framework for high-stakes decisions</p>
<p><strong>Afternoon: Your Custom ROI Calculator</strong> - Build your AI ROI calculator (track time saved, output increased, revenue impact) - Measure what matters: Operational leverage, not vanity metrics - The “10-Hour Rule” - how to save minimum 10 hours/week with AI - Final Q&amp;A: Troubleshooting your specific implementation challenges</p>
<p><strong>Deliverable:</strong> AI Governance Playbook + Custom ROI Calculator + Complete AI Profit OS</p>
</section>
</div>
</section>
<section id="meet-your-instructor-jitin-kapila" class="level2">
<h2 class="anchored" data-anchor-id="meet-your-instructor-jitin-kapila">Meet Your Instructor: Jitin Kapila</h2>
<div class="grid">
<div class="g-col-6 g-row-md-auto">
<p><strong>Ex-Fortune 500 AI Lead. Managed $80M+ Portfolios.</strong></p>
<p><span class="timeline-item"><strong>“I don’t teach theory. I build enterprise-grade systems.”</strong></span></p>
<p><strong>Background:</strong> - 14+ years architecting AI solutions for Fortune 500 enterprises - Managed portfolios exceeding $80M across automotive, retail, FMCG, telecommunications - Mechanical Engineering + Applied Mathematics background - <strong>Not a career educator - a practitioner who teaches</strong></p>
<p><strong>Track Record:</strong> - ₹6.9Cr annual savings (grocery chain spoilage reduction) - $11M operational optimization (automotive inventory system) - £80K/month revenue lift (retail predictive forecasting) - 45,000-unit inventory reduction (supply chain optimization)</p>
<p><strong>Philosophy:</strong> Senior professionals don’t need more theory. They need operational systems that create leverage. The AI Profit OS isn’t a course - it’s a toolkit you’ll use every day for the next decade.</p>
</div>
<div class="g-col-6 g-row-md-auto">
<p><img src="img/display_image.jpg" class="img-fluid figure-img" style="width:30em;border-radius: 50%;text-align: center;" data-border-radius="50%"></p>
</div>
</div>
</section>
<section id="what-senior-professionals-are-saying" class="level2">
<h2 class="anchored" data-anchor-id="what-senior-professionals-are-saying">What Senior Professionals Are Saying</h2>
<div class="grid">
<div class="g-col-6 g-col-md-auto">
<p>“I had the pleasure of working with Jitin for over two years (2023–2025) on a high-intensity AI program that was both technically complex and highly impactful for the business. Jitin played a pivotal role not only in experimenting with and developing the AI-driven forecasting solution but also in serving as an AI coach for end users, helping them understand and trust the forecasts produced by the model(s).</p>
<p>His deep data science expertise, combined with his ability to translate technical concepts into clear business language, made a remarkable difference in co-creating a truly futuristic AI product.”</p>
<p><strong>— Nikhil Jain, Head of Tech Accelerator &amp; AI Innovation</strong> <em>Client engagement: 2023-2025</em></p>
</div>
<div class="g-col-6 g-col-md-auto">
<p>“Jitin has the profound expertise of advanced level of R and Python. Many people at Harman Connected Services find his enthusiasm and dedication both inspiring and motivating. He showed a high level of command on Data Science, Machine Learning techniques and was a valuable contributor to our projects. He learns quickly and I would have no hesitation in working with Jitin once again in the future.”</p>
<p><strong>— Aasheesh Barvey, Data-Informed Decision-Making &amp; Advanced Analytics</strong> <em>Senior Manager, Strategy &amp; Project Management</em></p>
</div>
<div class="g-col-6 g-col-md-auto">
<p>“Jitin Kapila is a transformed data scientist with huge enthusiasm to learn new things. I have seen him growing from level to level in data science. Clarity of thoughts and out of the box thinking comes naturally to him.</p>
<p>He is a master class coding hand and can decompose any hard problem into simple logic and quickly build a scalable and ready to implement solution. I would like to have him any day any time working with me.”</p>
<p><strong>— Kumarjit Pathak, Global AI &amp; Data Science Leader @ ABInBev</strong> <em>Daniel H. Wagner Prize Winner (INFORMS 2022) | Visionary Innovator</em></p>
</div>
</div>
</section>
<section id="everything-included-in-your-ai-profit-os" class="level2 padded bg-warm">
<h2 class="anchored" data-anchor-id="everything-included-in-your-ai-profit-os">Everything Included in Your AI Profit OS</h2>
<div class="value-grid">
<div class="value-item">
<p><strong>3 Full Days of Live Training</strong> Interactive sessions with direct access to 14+ years of Fortune 500 AI implementation experience <em>Value: ₹75,000</em></p>
</div>
<div class="value-item">
<p><strong>Your 90-Day AI Roadmap</strong> Personalized implementation plan - start saving time from Week 1 <em>Value: ₹50,000</em></p>
</div>
<div class="value-item">
<p><strong>Deep-Research Prompt System (Excel-Based)</strong> The same framework that saved ₹6.9Cr for the grocery chain <em>Value: ₹40,000</em></p>
</div>
<div class="value-item">
<p><strong>Data Asset Library Template</strong> Structure your expertise for AI consumption - build your “Second Brain” <em>Value: ₹25,000</em></p>
</div>
<div class="value-item">
<p><strong>AI Governance Playbooks</strong> Quality control systems for high-stakes AI decisions <em>Value: ₹30,000</em></p>
</div>
<div class="value-item">
<p><strong>Custom ROI Calculator</strong> Track time saved, output increased, revenue impact - measure what matters <em>Value: ₹20,000</em></p>
</div>
<div class="value-item">
<p><strong>Lifetime Recording Access</strong> All sessions recorded, plus framework updates as systems evolve <em>Value: ₹15,000</em></p>
</div>
<div class="value-item">
<p><strong>Private Community Access</strong> Ongoing support with fellow AI Profit OS users, monthly office hours with Jitin <em>Value: ₹25,000</em></p>
</div>
<div class="value-total">
<p><strong>Total Value: ₹2,80,000</strong> <strong>Founding Cohort Investment: ₹7,490</strong> (Saves ₹2,75,001) <strong>Regular Price: ₹16,650</strong> (after founding cohort closes)</p>
</div>
</div>
</section>
<section id="the-unheard-of-guarantee" class="level2 cta-section">
<h2 class="anchored" data-anchor-id="the-unheard-of-guarantee">The “Unheard Of” Guarantee</h2>
<p><strong>If you don’t save at least 10 hours of work per week using the AI Profit OS within 30 days, I will refund you and pay you ₹5,000 for wasting your time.</strong></p>
<p>Yes, you read that right.</p>
<p><strong>Refund + ₹5,000 penalty paid to you.</strong></p>
<p>Why am I this confident? Because the system works. The grocery chain saved ₹6.9Cr. The automotive client saved $11M. The retail client generates £80K/month additional revenue.</p>
<p>If you implement the frameworks and don’t save minimum 10 hours per week, I’ve failed you - and I’ll pay for it.</p>
<p><strong>To claim:</strong> Email me within 30 days with (a) your 90-day roadmap, (b) evidence of implementation, (c) time tracking showing &lt;10 hours saved. If you did the work and didn’t get results, you get refund + ₹5,000.</p>
</section>
<section id="frequently-asked-questions" class="level2">
<h2 class="anchored" data-anchor-id="frequently-asked-questions">Frequently Asked Questions</h2>
<p></p><div id="ac-1" class="accordion quarto-accordion">
<div class="accordion-item">
<div class="accordion-header" id="heading-ac-1-wtocodeesystems">
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-ac-1-wtocodeesystems" aria-expanded="false" aria-controls="collapse-ac-1-wtocodeesystems">
<div class="accordion-header-content">Do I need to know how to code?</div></button>
</div>
<div id="collapse-ac-1-wtocodeesystems" class="accordion-collapse collapse" aria-labelledby="heading-ac-1-wtocodeesystems" data-bs-parent="ac-1">
<div class="accordion-body">
<div class="accordion-body-content">No.&nbsp;The AI Profit OS is designed for senior professionals, not engineers. Everything is built in Excel + simple tools you already use. If you can use Google Sheets, you can build these systems.</div></div>
</div>
</div>
<div class="accordion-item">
<div class="accordion-header" id="heading-ac-1-tofollownalizeai">
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-ac-1-tofollownalizeai" aria-expanded="false" aria-controls="collapse-ac-1-tofollownalizeai">
<div class="accordion-header-content">I’m not technical. Will I be able to follow?</div></button>
</div>
<div id="collapse-ac-1-tofollownalizeai" class="accordion-collapse collapse" aria-labelledby="heading-ac-1-tofollownalizeai" data-bs-parent="ac-1">
<div class="accordion-body">
<div class="accordion-body-content">Absolutely. This training is designed for business leaders, not data scientists. I’ve trained CFOs, COOs, and Senior Directors with zero technical background. If you can manage a P&amp;L, you can operationalize AI.</div></div>
</div>
</div>
<div class="accordion-item">
<div class="accordion-header" id="heading-ac-1-dayslivedinglive">
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-ac-1-dayslivedinglive" aria-expanded="false" aria-controls="collapse-ac-1-dayslivedinglive">
<div class="accordion-header-content">What if I can’t attend all 3 days live?</div></button>
</div>
<div id="collapse-ac-1-dayslivedinglive" class="accordion-collapse collapse" aria-labelledby="heading-ac-1-dayslivedinglive" data-bs-parent="ac-1">
<div class="accordion-body">
<div class="accordion-body-content">You’ll get lifetime recording access. However, the live workshops where you build YOUR specific systems are where the real value comes from. We strongly recommend attending live.</div></div>
</div>
</div>
<div class="accordion-item">
<div class="accordion-header" id="heading-ac-1-traininghatworks">
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-ac-1-traininghatworks" aria-expanded="false" aria-controls="collapse-ac-1-traininghatworks">
<div class="accordion-header-content">Is this just ChatGPT training?</div></button>
</div>
<div id="collapse-ac-1-traininghatworks" class="accordion-collapse collapse" aria-labelledby="heading-ac-1-traininghatworks" data-bs-parent="ac-1">
<div class="accordion-body">
<div class="accordion-body-content">No.&nbsp;ChatGPT is one tool in the AI Profit OS, but the system is much bigger. You’ll learn: (a) How to structure your workflow for AI leverage, (b) How to build repeatable systems (not one-off prompts), (c) How to measure ROI and scale what works.</div></div>
</div>
</div>
<div class="accordion-item">
<div class="accordion-header" id="heading-ac-1-workforagnostic">
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-ac-1-workforagnostic" aria-expanded="false" aria-controls="collapse-ac-1-workforagnostic">
<div class="accordion-header-content">What industries does this work for?</div></button>
</div>
<div id="collapse-ac-1-workforagnostic" class="accordion-collapse collapse" aria-labelledby="heading-ac-1-workforagnostic" data-bs-parent="ac-1">
<div class="accordion-body">
<div class="accordion-body-content">If you’re a senior professional doing knowledge work, this works. I’ve deployed AI systems across automotive, retail, FMCG, telecommunications, finance, and healthcare. The frameworks are industry-agnostic.</div></div>
</div>
</div>
<div class="accordion-item">
<div class="accordion-header" id="heading-ac-1-ndpolicycolleague">
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-ac-1-ndpolicycolleague" aria-expanded="false" aria-controls="collapse-ac-1-ndpolicycolleague">
<div class="accordion-header-content">What’s the refund policy?</div></button>
</div>
<div id="collapse-ac-1-ndpolicycolleague" class="accordion-collapse collapse" aria-labelledby="heading-ac-1-ndpolicycolleague" data-bs-parent="ac-1">
<div class="accordion-body">
<div class="accordion-body-content">The “Unheard Of” Guarantee (see above). If you implement the system and don’t save 10+ hours/week within 30 days, refund + ₹5,000 paid to you. After 30 days, no refunds - but you can transfer your seat to a colleague.</div></div>
</div>
</div>
<div class="accordion-item">
<div class="accordion-header" id="heading-ac-1-gmyteamadoption">
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-ac-1-gmyteamadoption" aria-expanded="false" aria-controls="collapse-ac-1-gmyteamadoption">
<div class="accordion-header-content">Can I bring my team?</div></button>
</div>
<div id="collapse-ac-1-gmyteamadoption" class="accordion-collapse collapse" aria-labelledby="heading-ac-1-gmyteamadoption" data-bs-parent="ac-1">
<div class="accordion-body">
<div class="accordion-body-content">Yes! We offer team pricing for 3+ participants from the same organization. Email jitin@jitinkapila.com for custom team rates. (Recommended: Bring 2-3 key leaders to accelerate adoption.)</div></div>
</div>
</div>
<div class="accordion-item">
<div class="accordion-header" id="heading-ac-1-icoursesyoutime">
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-ac-1-icoursesyoutime" aria-expanded="false" aria-controls="collapse-ac-1-icoursesyoutime">
<div class="accordion-header-content">How is this different from other AI courses?</div></button>
</div>
<div id="collapse-ac-1-icoursesyoutime" class="accordion-collapse collapse" aria-labelledby="heading-ac-1-icoursesyoutime" data-bs-parent="ac-1">
<div class="accordion-body">
<div class="accordion-body-content">Most AI courses teach theory or simple prompting. The AI Profit OS is a complete operational system you’ll deploy in your workflow. You’re not learning about AI - you’re building leverage. By Day 3, you have working systems saving you time.</div></div>
</div>
</div>
<div class="accordion-item">
<div class="accordion-header" id="heading-ac-1-outdatedkupdates">
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-ac-1-outdatedkupdates" aria-expanded="false" aria-controls="collapse-ac-1-outdatedkupdates">
<div class="accordion-header-content">What if AI changes? Will this become outdated?</div></button>
</div>
<div id="collapse-ac-1-outdatedkupdates" class="accordion-collapse collapse" aria-labelledby="heading-ac-1-outdatedkupdates" data-bs-parent="ac-1">
<div class="accordion-body">
<div class="accordion-body-content">The OLCD Protocol, AI-ART Matrix, and operational frameworks are model-agnostic. Whether it’s ChatGPT, Claude, Gemini, or whatever comes next, the system adapts. Plus, you get lifetime access to framework updates.</div></div>
</div>
</div>
</div>
<p></p>
</section>
<section id="founding-cohort-december-19-21-2025" class="level2 padded text-center">
<h2 class="anchored" data-anchor-id="founding-cohort-december-19-21-2025">Founding Cohort: December 19-21, 2025</h2>
<div class="scarcity-box">
<p><strong>Only 12 Seats Remaining</strong> (of 20 total)</p>
<p>We deliberately keep cohorts small to ensure personalized feedback on your AI systems and deep troubleshooting for your specific use case.</p>
<p><strong>Founding Cohort Pricing Ends:</strong> When all 20 seats fill OR December 10, 2025 (whichever comes first)</p>
<p>After upcoming cohort closes, price increases to ₹16,650 permanently.</p>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Upcoming Cohort (12 seats left)</th>
<th>Regular Price</th>
<th>My Consulting Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>₹7,490</strong></td>
<td>₹16,650</td>
<td>$185/hour</td>
</tr>
<tr class="even">
<td>Save ₹1,58,575 in value</td>
<td>Standard rate</td>
<td>(200+ hours of frameworks)</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="ready-to-build-your-ai-profit-os" class="level2 padded text-center">
<h2 class="anchored" data-anchor-id="ready-to-build-your-ai-profit-os">Ready to Build Your AI Profit OS?</h2>
<p><strong>Investment:</strong> ₹7,490 (Founding Cohort) | ₹16,650(including GST) (Regular) <strong>Next Cohort:</strong> December 19-21, 2025 <strong>Seats Remaining:</strong> 12 of 20</p>
<p><span class="btn-primary btn-large" style="text-wrap-mode: nowrap;">Secure Your Seat Now <em>at ₹7,490 Only</em></span></p>
<div style="margin-top: 1.5rem; font-size: 0.875rem; color: $body-color;">
<p><strong>The “Unheard Of” Guarantee:</strong> If you don’t save 10+ hours/week within 30 days, refund + ₹5,000 paid to you.</p>
</div>
<div class="mt-lg">
<p><strong>Questions?</strong> <a href="mailto:info@kriyalytics.com">Email me directly</a> Or schedule a <a href="https://cal.com/jitink-kriyalytics/strategy-consulting">15-minute clarity call</a></p>
</div>
</section>
<section id="still-on-the-fence" class="level2 padded bg-warm">
<h2 class="anchored" data-anchor-id="still-on-the-fence">Still On The Fence?</h2>
<p></p><div id="ac-2" class="accordion quarto-accordion">
<div class="accordion-item">
<div class="accordion-header" id="heading-ac-2-stryrolerreality">
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-ac-2-stryrolerreality" aria-expanded="false" aria-controls="collapse-ac-2-stryrolerreality">
<div class="accordion-header-content">I’m not sure this will work for my specific industry/role.</div></button>
</div>
<div id="collapse-ac-2-stryrolerreality" class="accordion-collapse collapse" aria-labelledby="heading-ac-2-stryrolerreality" data-bs-parent="ac-2">
<div class="accordion-body">
<div class="accordion-body-content">That’s exactly why Day 1 is focused on YOUR workflow and YOUR 90-day roadmap. The frameworks are industry-agnostic, but the implementation is personalized to your reality.</div></div>
</div>
</div>
<div class="accordion-item">
<div class="accordion-header" id="heading-ac-2-training8000">
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-ac-2-training8000" aria-expanded="false" aria-controls="collapse-ac-2-training8000">
<div class="accordion-header-content">₹7,999 feels expensive for a training.</div></button>
</div>
<div id="collapse-ac-2-training8000" class="accordion-collapse collapse" aria-labelledby="heading-ac-2-training8000" data-bs-parent="ac-2">
<div class="accordion-body">
<div class="accordion-body-content">Compare it to: - (a) One hour of my consulting at ₹25,000/hour, -(b) The cost of being replaced by a 22-year-old who knows how to use AI, -(c) The ₹6.9Cr the grocery chain saved with this exact system. If you don’t save 10+ hours/week, I’ll refund you AND pay you ₹8,000.</div></div>
</div>
</div>
<div class="accordion-item">
<div class="accordion-header" id="heading-ac-2-hisaloneavailable">
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-ac-2-hisaloneavailable" aria-expanded="false" aria-controls="collapse-ac-2-hisaloneavailable">
<div class="accordion-header-content">What if I can’t implement this alone?</div></button>
</div>
<div id="collapse-ac-2-hisaloneavailable" class="accordion-collapse collapse" aria-labelledby="heading-ac-2-hisaloneavailable" data-bs-parent="ac-2">
<div class="accordion-body">
<div class="accordion-body-content">You won’t be alone. You’ll join a private community of senior professionals building AI systems. Plus monthly office hours with me. And if you need hands-on implementation support, 1:1 consulting is available.</div></div>
</div>
</div>
<div class="accordion-item">
<div class="accordion-header" id="heading-ac-2-justhypeleverage">
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-ac-2-justhypeleverage" aria-expanded="false" aria-controls="collapse-ac-2-justhypeleverage">
<div class="accordion-header-content">How do I know this isn’t just hype?</div></button>
</div>
<div id="collapse-ac-2-justhypeleverage" class="accordion-collapse collapse" aria-labelledby="heading-ac-2-justhypeleverage" data-bs-parent="ac-2">
<div class="accordion-body">
<div class="accordion-body-content">Look at the results: ₹6.9Cr grocery chain savings. $11M automotive optimization. £80K/month retail revenue lift. These are real deployments at Mercedes, L’Oréal, Maruti, British Telecom. This isn’t theory - it’s operational leverage.</div></div>
</div>
</div>
<div class="accordion-item">
<div class="accordion-header" id="heading-ac-2-meanywayexpertise">
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-ac-2-meanywayexpertise" aria-expanded="false" aria-controls="collapse-ac-2-meanywayexpertise">
<div class="accordion-header-content">What if AI replaces me anyway?</div></button>
</div>
<div id="collapse-ac-2-meanywayexpertise" class="accordion-collapse collapse" aria-labelledby="heading-ac-2-meanywayexpertise" data-bs-parent="ac-2">
<div class="accordion-body">
<div class="accordion-body-content">AI will replace professionals who DON’T learn to operationalize it. Senior professionals who build AI systems become 10x more valuable. You’re not competing with AI - you’re building leverage ON TOP of your 10+ years of expertise.</div></div>
</div>
</div>
</div>
<p></p>
</section>



<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/jitinkapila\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Jitin Kapila - All rights reserved</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/jitinkapila">
      <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/jitinkapila">
      <i class="bi bi-twitter" role="img" aria-label="Twitter">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/jkapila">
      <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.youtube.com/@jitinkapila">
      <i class="bi bi-youtube" role="img" aria-label="YouTube">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://aicrosscurrent.substack.com/">
      <i class="bi bi-substack" role="img" aria-label="Substack Newsletter">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://instagram.com/jitinkapila">
      <i class="bi bi-instagram" role="img" aria-label="Instagram">
</i> 
    </a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://cal.com/jitink-kriyalytics/strategy-consulting">
<p>Consulting</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="./404.html">
<p>Privacy</p>
</a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="./posts/index.xml">
      <i class="bi bi-rss" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>